### ISSUE TITLE
Any plans to release the training code?

### ISSUE THREAD

**Issue by greeneggsandyaml** [weijiawu/Synthetic-to-Real-Unsupervised-Domain-Adaptation-for-Scene-Text-Detection-in-the-Wild#3]
Hi authors,

Thank you for your great work. Will you be releasing the training code? It's been "TBD" for quite a while. 

Best,

**Comment by weijiawu** [comment]
The training code will be released In twenty days, thank for your attention.

**Comment by WeihongM** [comment]
@weijiawu Hello, impressed by your work.
May I ask when the code will be updated?

**Comment by WeihongM** [comment]
Hello,  any reply?
 @weijiawu

**Comment by weijiawu** [comment]
So sorry, the training code will be released before June 15th.  Over the past month, I'm busy with another task.

**Comment by WeihongM** [comment]
Thanks, Looking forward to your updates.

**Comment by doem97** [comment]
Thanks. Waiting for your code :)

**Comment by WeihongM** [comment]
aha, Tomorrow is June 15th, will the code be updated?

**Comment by WeihongM** [comment]
aha, Tomorrow is June 15th, will the code be updated?  @weijiawu
