### ISSUE TITLE
Mask all the groudtruth (for target domain, the pseudo label) 

### ISSUE THREAD

**Issue by doem97** [weijiawu/Synthetic-to-Real-Unsupervised-Domain-Adaptation-for-Scene-Text-Detection-in-the-Wild#7]
https://github.com/weijiawu/SyntoReal_STD/blob/02ee312504d754bf51d5149916235110d5283105/dataset/ICDAR15.py#L330

Sorry but I think this is really not a code that can be followed up with. In this line, the data loader for ICDAR15 masked all the predictions which troubled me for a long while :( 

I'd recommend followers wait for further updates or bug fixes from the author, otherwise, you may run into random logic bugs. If you insist, be reminded to fix the above prob.

Besides, I will also release a related but not exactly re-implement of syn2real later.

**Comment by weijiawu** [comment]
For transferring SynthText to ICDAR2015

target domain: unlabeled images on ICDAR2015
source domain: images with annotation on SynthText
pseudo label: the annotation for unlabeled images on ICDAR2015

Thank you for the re-implement for syn2real. Sorry, most recently, I can not update and fix the bugs due to many personal reasons.

**Comment by doem97** [comment]
> For transferring SynthText to ICDAR2015
> 
> target domain: unlabeled images on ICDAR2015
> source domain: images with annotation on SynthText
> pseudo label: the annotation for unlabeled images on ICDAR2015
> 
> Thank you for the re-implement for syn2real. Sorry, most recently, I can not update and fix the bugs due to many personal reasons.

thanks for the reply. I see. In the above code, all the pseudo labels are set as 'ignored' thus not attending the training, which is not reasonable. 

The proper way is to set: 'text area' (the predicted boxes, or the positive pseudo label), 'background' (predicted background, negative pseudo label), 'uncertain' (the area that not confident thus should be ignored.)
